version: "3.7"
services:
  app:
    build:
      args:
        user: supera
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: supera
    container_name: supera-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - supera

  db:
    image: mysql:5.7
    container_name: supera-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - supera

  nginx:
    image: nginx:alpine
    container_name: supera-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - supera

volumes:
  supera:
networks:
  supera:
    driver: bridge
